export const emojiList = [
  {
    id: 1,
    emoji: "😀",
    description: "grinning face",
    category: "Smileys & Emotion",
    aliases: ["grinning"],
    tags: ["smile", "happy"],
  },
  {
    id: 2,
    emoji: "😃",
    description: "grinning face with big eyes",
    category: "Smileys & Emotion",
    aliases: ["smiley"],
    tags: ["happy", "joy", "haha"],
  },
  {
    id: 3,
    emoji: "😄",
    description: "grinning face with smiling eyes",
    category: "Smileys & Emotion",
    aliases: ["smile"],
    tags: ["happy", "joy", "laugh", "pleased"],
  },
  {
    id: 4,
    emoji: "😁",
    description: "beaming face with smiling eyes",
    category: "Smileys & Emotion",
    aliases: ["grin"],
    tags: [],
  },
  {
    id: 5,
    emoji: "😆",
    description: "grinning squinting face",
    category: "Smileys & Emotion",
    aliases: ["laughing", "satisfied"],
    tags: ["happy", "haha"],
  },
  {
    id: 6,
    emoji: "😅",
    description: "grinning face with sweat",
    category: "Smileys & Emotion",
    aliases: ["sweat_smile"],
    tags: ["hot"],
  },
  {
    id: 7,
    emoji: "🤣",
    description: "rolling on the floor laughing",
    category: "Smileys & Emotion",
    aliases: ["rofl"],
    tags: ["lol", "laughing"],
  },
  {
    id: 8,
    emoji: "😂",
    description: "face with tears of joy",
    category: "Smileys & Emotion",
    aliases: ["joy"],
    tags: ["tears"],
  },
  {
    id: 9,
    emoji: "🙂",
    description: "slightly smiling face",
    category: "Smileys & Emotion",
    aliases: ["slightly_smiling_face"],
    tags: [],
  },
  {
    id: 10,
    emoji: "🙃",
    description: "upside-down face",
    category: "Smileys & Emotion",
    aliases: ["upside_down_face"],
    tags: [],
  },
  {
    id: 11,
    emoji: "🫠",
    description: "melting face",
    category: "Smileys & Emotion",
    aliases: ["melting_face"],
    tags: ["sarcasm", "dread"],
  },
  {
    id: 12,
    emoji: "😉",
    description: "winking face",
    category: "Smileys & Emotion",
    aliases: ["wink"],
    tags: ["flirt"],
  },
  {
    id: 13,
    emoji: "😊",
    description: "smiling face with smiling eyes",
    category: "Smileys & Emotion",
    aliases: ["blush"],
    tags: ["proud"],
  },
  {
    id: 14,
    emoji: "😇",
    description: "smiling face with halo",
    category: "Smileys & Emotion",
    aliases: ["innocent"],
    tags: ["angel"],
  },
  {
    id: 15,
    emoji: "🥰",
    description: "smiling face with hearts",
    category: "Smileys & Emotion",
    aliases: ["smiling_face_with_three_hearts"],
    tags: ["love"],
  },
  {
    id: 16,
    emoji: "😍",
    description: "smiling face with heart-eyes",
    category: "Smileys & Emotion",
    aliases: ["heart_eyes"],
    tags: ["love", "crush"],
  },
  {
    id: 17,
    emoji: "🤩",
    description: "star-struck",
    category: "Smileys & Emotion",
    aliases: ["star_struck"],
    tags: ["eyes"],
  },
  {
    id: 18,
    emoji: "😘",
    description: "face blowing a kiss",
    category: "Smileys & Emotion",
    aliases: ["kissing_heart"],
    tags: ["flirt"],
  },
  {
    id: 19,
    emoji: "😗",
    description: "kissing face",
    category: "Smileys & Emotion",
    aliases: ["kissing"],
    tags: [],
  },
  {
    id: 20,
    emoji: "😑",
    description: "expressionless face",
    category: "Smileys & Emotion",
    aliases: ["expressionless"],
    tags: [],
  },
  {
    id: 21,
    emoji: "😚",
    description: "kissing face with closed eyes",
    category: "Smileys & Emotion",
    aliases: ["kissing_closed_eyes"],
    tags: [],
  },
  {
    id: 22,
    emoji: "😙",
    description: "kissing face with smiling eyes",
    category: "Smileys & Emotion",
    aliases: ["kissing_smiling_eyes"],
    tags: [],
  },
  {
    id: 23,
    emoji: "🥲",
    description: "smiling face with tear",
    category: "Smileys & Emotion",
    aliases: ["smiling_face_with_tear"],
    tags: [],
  },
  {
    id: 24,
    emoji: "😋",
    description: "face savoring food",
    category: "Smileys & Emotion",
    aliases: ["yum"],
    tags: ["tongue", "lick"],
  },
  {
    id: 25,
    emoji: "😛",
    description: "face with tongue",
    category: "Smileys & Emotion",
    aliases: ["stuck_out_tongue"],
    tags: [],
  },
  {
    id: 26,
    emoji: "😜",
    description: "winking face with tongue",
    category: "Smileys & Emotion",
    aliases: ["stuck_out_tongue_winking_eye"],
    tags: ["prank", "silly"],
  },
  {
    id: 27,
    emoji: "🤪",
    description: "zany face",
    category: "Smileys & Emotion",
    aliases: ["zany_face"],
    tags: ["goofy", "wacky"],
  },
  {
    id: 28,
    emoji: "😝",
    description: "squinting face with tongue",
    category: "Smileys & Emotion",
    aliases: ["stuck_out_tongue_closed_eyes"],
    tags: ["prank"],
  },
  {
    id: 29,
    emoji: "🤑",
    description: "money-mouth face",
    category: "Smileys & Emotion",
    aliases: ["money_mouth_face"],
    tags: ["rich"],
  },
  {
    id: 30,
    emoji: "🤗",
    description: "smiling face with open hands",
    category: "Smileys & Emotion",
    aliases: ["hugs"],
    tags: [],
  },
  {
    id: 31,

    emoji: "🤭",
    description: "face with hand over mouth",
    category: "Smileys & Emotion",
    aliases: ["hand_over_mouth"],
    tags: ["quiet", "whoops"],
  },
  {
    id: 32,

    emoji: "🫢",
    description: "face with open eyes and hand over mouth",
    category: "Smileys & Emotion",
    aliases: ["face_with_open_eyes_and_hand_over_mouth"],
    tags: ["gasp", "shock"],
  },
  {
    id: 33,

    emoji: "🫣",
    description: "face with peeking eye",
    category: "Smileys & Emotion",
    aliases: ["face_with_peeking_eye"],
    tags: [],
  },
  {
    id: 34,

    emoji: "🤫",
    description: "shushing face",
    category: "Smileys & Emotion",
    aliases: ["shushing_face"],
    tags: ["silence", "quiet"],
  },
  {
    id: 35,

    emoji: "🤔",
    description: "thinking face",
    category: "Smileys & Emotion",
    aliases: ["thinking"],
    tags: [],
  },
  {
    id: 36,

    emoji: "🫡",
    description: "saluting face",
    category: "Smileys & Emotion",
    aliases: ["saluting_face"],
    tags: ["respect"],
  },
  {
    id: 37,

    emoji: "🤐",
    description: "zipper-mouth face",
    category: "Smileys & Emotion",
    aliases: ["zipper_mouth_face"],
    tags: ["silence", "hush"],
  },
  {
    id: 38,

    emoji: "🤨",
    description: "face with raised eyebrow",
    category: "Smileys & Emotion",
    aliases: ["raised_eyebrow"],
    tags: ["suspicious"],
  },
  {
    id: 39,

    emoji: "😐",
    description: "neutral face",
    category: "Smileys & Emotion",
    aliases: ["neutral_face"],
    tags: ["meh"],
  },

  //   {
  //     emoji: "😶",
  //     description: "face without mouth",
  //     category: "Smileys & Emotion",
  //     aliases: ["no_mouth"],
  //     tags: ["mute", "silence"],
  //   },
  //   {
  //     emoji: "🫥",
  //     description: "dotted line face",
  //     category: "Smileys & Emotion",
  //     aliases: ["dotted_line_face"],
  //     tags: ["invisible"],
  //   },
  //   {
  //     emoji: "😶‍🌫️",
  //     description: "face in clouds",
  //     category: "Smileys & Emotion",
  //     aliases: ["face_in_clouds"],
  //     tags: [],
  //   },
  //   {
  //     emoji: "😏",
  //     description: "smirking face",
  //     category: "Smileys & Emotion",
  //     aliases: ["smirk"],
  //     tags: ["smug"],
  //   },
  //   {
  //     emoji: "😒",
  //     description: "unamused face",
  //     category: "Smileys & Emotion",
  //     aliases: ["unamused"],
  //     tags: ["meh"],
  //   },
  //   {
  //     emoji: "🙄",
  //     description: "face with rolling eyes",
  //     category: "Smileys & Emotion",
  //     aliases: ["roll_eyes"],
  //     tags: [],
  //   },
  //   {
  //     emoji: "😬",
  //     description: "grimacing face",
  //     category: "Smileys & Emotion",
  //     aliases: ["grimacing"],
  //     tags: [],
  //   },
  //   {
  //     emoji: "😮‍💨",
  //     description: "face exhaling",
  //     category: "Smileys & Emotion",
  //     aliases: ["face_exhaling"],
  //     tags: [],
  //   },
  //   {
  //     emoji: "🤥",
  //     description: "lying face",
  //     category: "Smileys & Emotion",
  //     aliases: ["lying_face"],
  //     tags: ["liar"],
  //   },
  //   {
  //     emoji: "🫨",
  //     description: "shaking face",
  //     category: "Smileys & Emotion",
  //     aliases: ["shaking_face"],
  //     tags: ["shock"],
  //   },
  //   {
  //     emoji: "😌",
  //     description: "relieved face",
  //     category: "Smileys & Emotion",
  //     aliases: ["relieved"],
  //     tags: ["whew"],
  //   },
  //   {
  //     emoji: "😔",
  //     description: "pensive face",
  //     category: "Smileys & Emotion",
  //     aliases: ["pensive"],
  //     tags: [],
  //   },
  //   {
  //     emoji: "😪",
  //     description: "sleepy face",
  //     category: "Smileys & Emotion",
  //     aliases: ["sleepy"],
  //     tags: ["tired"],
  //   },
  //   {
  //     emoji: "🤤",
  //     description: "drooling face",
  //     category: "Smileys & Emotion",
  //     aliases: ["drooling_face"],
  //     tags: [],
  //   },
  //   {
  //     emoji: "😴",
  //     description: "sleeping face",
  //     category: "Smileys & Emotion",
  //     aliases: ["sleeping"],
  //     tags: ["zzz"],
  //   },
  //   {
  //     emoji: "😷",
  //     description: "face with medical mask",
  //     category: "Smileys & Emotion",
  //     aliases: ["mask"],
  //     tags: ["sick", "ill"],
  //   },
  //   {
  //     emoji: "🤒",
  //     description: "face with thermometer",
  //     category: "Smileys & Emotion",
  //     aliases: ["face_with_thermometer"],
  //     tags: ["sick"],
  //   },
  //   {
  //     emoji: "🤕",
  //     description: "face with head-bandage",
  //     category: "Smileys & Emotion",
  //     aliases: ["face_with_head_bandage"],
  //     tags: ["hurt"],
  //   },
  //   {
  //     emoji: "🤢",
  //     description: "nauseated face",
  //     category: "Smileys & Emotion",
  //     aliases: ["nauseated_face"],
  //     tags: ["sick", "barf", "disgusted"],
  //   },
  //   {
  //     emoji: "🤮",
  //     description: "face vomiting",
  //     category: "Smileys & Emotion",
  //     aliases: ["vomiting_face"],
  //     tags: ["barf", "sick"],
  //   },
  //   {
  //     emoji: "🤧",
  //     description: "sneezing face",
  //     category: "Smileys & Emotion",
  //     aliases: ["sneezing_face"],
  //     tags: ["achoo", "sick"],
  //   },
  //   {
  //     emoji: "🥵",
  //     description: "hot face",
  //     category: "Smileys & Emotion",
  //     aliases: ["hot_face"],
  //     tags: ["heat", "sweating"],
  //   },
  //   {
  //     emoji: "🥶",
  //     description: "cold face",
  //     category: "Smileys & Emotion",
  //     aliases: ["cold_face"],
  //     tags: ["freezing", "ice"],
  //   },
  //   {
  //     emoji: "🥴",
  //     description: "woozy face",
  //     category: "Smileys & Emotion",
  //     aliases: ["woozy_face"],
  //     tags: ["groggy"],
  //   },
  //   {
  //     emoji: "😵",
  //     description: "face with crossed-out eyes",
  //     category: "Smileys & Emotion",
  //     aliases: ["dizzy_face"],
  //     tags: [],
  //   },
  //   {
  //     emoji: "😵‍💫",
  //     description: "face with spiral eyes",
  //     category: "Smileys & Emotion",
  //     aliases: ["face_with_spiral_eyes"],
  //     tags: [],
  //   },
  //   {
  //     emoji: "🤯",
  //     description: "exploding head",
  //     category: "Smileys & Emotion",
  //     aliases: ["exploding_head"],
  //     tags: ["mind", "blown"],
  //   },
  //   {
  //     emoji: "🤠",
  //     description: "cowboy hat face",
  //     category: "Smileys & Emotion",
  //     aliases: ["cowboy_hat_face"],
  //     tags: [],
  //   },
  //   {
  //     emoji: "🥳",
  //     description: "partying face",
  //     category: "Smileys & Emotion",
  //     aliases: ["partying_face"],
  //     tags: ["celebration", "birthday"],
  //   },
  //   {
  //     emoji: "🥸",
  //     description: "disguised face",
  //     category: "Smileys & Emotion",
  //     aliases: ["disguised_face"],
  //     tags: [],
  //   },
  //   {
  //     emoji: "😎",
  //     description: "smiling face with sunglasses",
  //     category: "Smileys & Emotion",
  //     aliases: ["sunglasses"],
  //     tags: ["cool"],
  //   },
  //   {
  //     emoji: "🤓",
  //     description: "nerd face",
  //     category: "Smileys & Emotion",
  //     aliases: ["nerd_face"],
  //     tags: ["geek", "glasses"],
  //   },
  //   {
  //     emoji: "🧐",
  //     description: "face with monocle",
  //     category: "Smileys & Emotion",
  //     aliases: ["monocle_face"],
  //     tags: [],
  //   },
  //   {
  //     emoji: "😕",
  //     description: "confused face",
  //     category: "Smileys & Emotion",
  //     aliases: ["confused"],
  //     tags: [],
  //   },
  //   {
  //     emoji: "🫤",
  //     description: "face with diagonal mouth",
  //     category: "Smileys & Emotion",
  //     aliases: ["face_with_diagonal_mouth"],
  //     tags: ["confused"],
  //   },
  //   {
  //     emoji: "😟",
  //     description: "worried face",
  //     category: "Smileys & Emotion",
  //     aliases: ["worried"],
  //     tags: ["nervous"],
  //   },
  //   {
  //     emoji: "🙁",
  //     description: "slightly frowning face",
  //     category: "Smileys & Emotion",
  //     aliases: ["slightly_frowning_face"],
  //     tags: [],
  //   },
  //   {
  //     emoji: "☹️",
  //     description: "frowning face",
  //     category: "Smileys & Emotion",
  //     aliases: ["frowning_face"],
  //     tags: [],
  //   },
  //   {
  //     emoji: "😮",
  //     description: "face with open mouth",
  //     category: "Smileys & Emotion",
  //     aliases: ["open_mouth"],
  //     tags: ["surprise", "impressed", "wow"],
  //   },
  //   {
  //     emoji: "😯",
  //     description: "hushed face",
  //     category: "Smileys & Emotion",
  //     aliases: ["hushed"],
  //     tags: ["silence", "speechless"],
  //   },
  //   {
  //     emoji: "😲",
  //     description: "astonished face",
  //     category: "Smileys & Emotion",
  //     aliases: ["astonished"],
  //     tags: ["amazed", "gasp"],
  //   },
  //   {
  //     emoji: "😳",
  //     description: "flushed face",
  //     category: "Smileys & Emotion",
  //     aliases: ["flushed"],
  //     tags: [],
  //   },
  //   {
  //     emoji: "🥺",
  //     description: "pleading face",
  //     category: "Smileys & Emotion",
  //     aliases: ["pleading_face"],
  //     tags: ["puppy", "eyes"],
  //   },
  //   {
  //     emoji: "🥹",
  //     description: "face holding back tears",
  //     category: "Smileys & Emotion",
  //     aliases: ["face_holding_back_tears"],
  //     tags: ["tears", "gratitude"],
  //   },
  //   {
  //     emoji: "😦",
  //     description: "frowning face with open mouth",
  //     category: "Smileys & Emotion",
  //     aliases: ["frowning"],
  //     tags: [],
  //   },
  //   {
  //     emoji: "😧",
  //     description: "anguished face",
  //     category: "Smileys & Emotion",
  //     aliases: ["anguished"],
  //     tags: ["stunned"],
  //   },
  //   {
  //     emoji: "😨",
  //     description: "fearful face",
  //     category: "Smileys & Emotion",
  //     aliases: ["fearful"],
  //     tags: ["scared", "shocked", "oops"],
  //   },
  //   {
  //     emoji: "😰",
  //     description: "anxious face with sweat",
  //     category: "Smileys & Emotion",
  //     aliases: ["cold_sweat"],
  //     tags: ["nervous"],
  //   },
  //   {
  //     emoji: "😥",
  //     description: "sad but relieved face",
  //     category: "Smileys & Emotion",
  //     aliases: ["disappointed_relieved"],
  //     tags: ["phew", "sweat", "nervous"],
  //   },
  //   {
  //     emoji: "😢",
  //     description: "crying face",
  //     category: "Smileys & Emotion",
  //     aliases: ["cry"],
  //     tags: ["sad", "tear"],
  //   },
  //   {
  //     emoji: "😭",
  //     description: "loudly crying face",
  //     category: "Smileys & Emotion",
  //     aliases: ["sob"],
  //     tags: ["sad", "cry", "bawling"],
  //   },
  //   {
  //     emoji: "😱",
  //     description: "face screaming in fear",
  //     category: "Smileys & Emotion",
  //     aliases: ["scream"],
  //     tags: ["horror", "shocked"],
  //   },
  //   {
  //     emoji: "😖",
  //     description: "confounded face",
  //     category: "Smileys & Emotion",
  //     aliases: ["confounded"],
  //     tags: [],
  //   },
  //   {
  //     emoji: "😣",
  //     description: "persevering face",
  //     category: "Smileys & Emotion",
  //     aliases: ["persevere"],
  //     tags: ["struggling"],
  //   },
  //   {
  //     emoji: "😞",
  //     description: "disappointed face",
  //     category: "Smileys & Emotion",
  //     aliases: ["disappointed"],
  //     tags: ["sad"],
  //   },
  //   {
  //     emoji: "😓",
  //     description: "downcast face with sweat",
  //     category: "Smileys & Emotion",
  //     aliases: ["sweat"],
  //     tags: [],
  //   },
  //   {
  //     emoji: "😩",
  //     description: "weary face",
  //     category: "Smileys & Emotion",
  //     aliases: ["weary"],
  //     tags: ["tired"],
  //   },
  //   {
  //     emoji: "😫",
  //     description: "tired face",
  //     category: "Smileys & Emotion",
  //     aliases: ["tired_face"],
  //     tags: ["upset", "whine"],
  //   },
  //   {
  //     emoji: "🥱",
  //     description: "yawning face",
  //     category: "Smileys & Emotion",
  //     aliases: ["yawning_face"],
  //     tags: [],
  //   },
  //   {
  //     emoji: "😤",
  //     description: "face with steam from nose",
  //     category: "Smileys & Emotion",
  //     aliases: ["triumph"],
  //     tags: ["smug"],
  //   },
  //   {
  //     emoji: "😡",
  //     description: "enraged face",
  //     category: "Smileys & Emotion",
  //     aliases: ["rage", "pout"],
  //     tags: ["angry"],
  //   },
  //   {
  //     emoji: "😠",
  //     description: "angry face",
  //     category: "Smileys & Emotion",
  //     aliases: ["angry"],
  //     tags: ["mad", "annoyed"],
  //   },
  //   {
  //     emoji: "🤬",
  //     description: "face with symbols on mouth",
  //     category: "Smileys & Emotion",
  //     aliases: ["cursing_face"],
  //     tags: ["foul"],
  //   },
];
